global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets:
      - 'prometheus:9090'
  - job_name: 'node'
    static_configs:
    - targets:
      - 'localhost:9100'
      labels:
        group: 'docker-host'
  - job_name: 'docker'
    static_configs:
    - targets:
      - 'cadvisor:8080'
      labels:
        group: 'docker-container'
